import { z } from "zod";

import { phrase } from "./primitives";

export const uiPagesSchema = z.object({
  news: z.object({
    title: phrase,
    lead: phrase,
    seoDescription: phrase,
    fallbackTitle: phrase,
    intro: phrase,
    introLinks: phrase,
    whoWas: phrase,
    whatToRebuild: phrase,
    howToHelp: phrase,
    unavailableTitle: phrase,
    emptyTitle: phrase,
    emptyBody: phrase,
    shareHeading: phrase,
    seeAll: phrase,
    seeTransparency: phrase,
    originalLanguage: phrase,
    introAnd: phrase,
  }),
  /* En el orden en que aparecen en la página, que desde ADR-024 es pérdida →
     comunidad → reconstrucción → legado. */
  home: z.object({
    locationLine: phrase,
    openingLead: phrase,
    openingNeed: phrase,
    quoteOverlay: phrase,
    knowStory: phrase,
    scrollHint: phrase,
    chapterWhatHappened: phrase,
    fireTitle: phrase,
    fireLead: phrase,
    houseNote: phrase,
    chapterCommunity: phrase,
    communityTitle: phrase,
    communityLead: phrase,
    communityNote: phrase,
    seeStory: phrase,
    chapterHelp: phrase,
    helpTitle: phrase,
    helpKicker: phrase,
    debrisTitle: phrase,
    debrisBody: phrase,
    materialsTitle: phrase,
    materialsBody: phrase,
    remoteTitle: phrase,
    remoteBody: phrase,
    whatsapp: phrase,
    call: phrase,
    chapterDonate: phrase,
    donateTitle: phrase,
    donateLead: phrase,
    transfer: phrase,
    mercadoPago: phrase,
    mercadoPagoLead: phrase,
    mercadoPagoCta: phrase,
    paypal: phrase,
    paypalLead: phrase,
    paypalCta: phrase,
    thanksNote: phrase,
    chapterNorma: phrase,
    normaLead: phrase,
    seeNorma: phrase,
    chapterNext: phrase,
    nextTitle: phrase,
    nextLead: phrase,
    nextBody: phrase,
    nextNote: phrase,
    menu: phrase,
    closeMenu: phrase,
    faqHeading: phrase,
  }),
  contactPage: z.object({
    title: phrase,
    seoDescription: phrase,
    lead: phrase,
    whatsapp: phrase,
    call: phrase,
  }),
  notFoundPage: z.object({
    title: phrase,
    lead: phrase,
    home: phrase,
  }),
  normaPage: z.object({
    title: phrase,
    seoDescription: phrase,
    contribution: phrase,
    privacyLink: phrase,
    photosNote: phrase,
    shareHeading: phrase,
    bookKicker: phrase,
    bookRead: phrase,
    bookDownload: phrase,
    quotesHeading: phrase,
  }),
  whatHappenedPage: z.object({
    seoDescription: phrase,
    whereLabel: phrase,
    whenLabel: phrase,
    whenValue: phrase,
    lostLabel: phrase,
    lostValue: phrase,
    photosHeading: phrase,
    seeBefore: phrase,
    rebuildLink: phrase,
    and: phrase,
    transparencyLink: phrase,
    end: phrase,
  }),
  reconstructionPage: z.object({
    seoDescription: phrase,
    workHeading: phrase,
    scopeHeading: phrase,
    budgetHeading: phrase,
    progressHeading: phrase,
    noMilestonesTitle: phrase,
    noMilestonesBody: phrase,
    photosNote: phrase,
    seeNews: phrase,
    helpHeading: phrase,
    helpLead: phrase,
  }),
  helpPage: z.object({
    seoDescription: phrase,
    beforeTransferTitle: phrase,
    beforeTransfer: phrase,
    accountsHeading: phrase,
    afterHeading: phrase,
    afterLinkLead: phrase,
    reportLink: phrase,
    afterLinkTail: phrase,
    shareHeading: phrase,
    shareLead: phrase,
  }),
  transparencyPage: z.object({
    seoDescription: phrase,
    totalsHeading: phrase,
    noReconciliation: phrase,
    reconciledOn: phrase,
    currenciesNote: phrase,
    staleTitle: phrase,
    staleBody: phrase,
    byCategoryHeading: phrase,
    ledgerHeading: phrase,
    noExpensesTitle: phrase,
    noExpensesBody: phrase,
    noReceipts: phrase,
    receiptsNote: phrase,
    methodHeading: phrase,
    helpHeading: phrase,
    helpLead: phrase,
    newsLink: phrase,
    helpLeadTail: phrase,
  }),
  legacyPage: z.object({
    seoDescription: phrase,
    statusTitle: phrase,
    statusBody: phrase,
    accountsLink: phrase,
    statusTail: phrase,
    houseFirst: phrase,
    houseFirstLead: phrase,
  }),
  legalPage: z.object({
    privacySeo: phrase,
    termsSeo: phrase,
  }),
});
